sonata_user:
    manager_type: orm
    class:
        user: App\Entity\User
        group: App\Entity\Group
    admin:
      user:
        class: App\Admin\UserAdmin
        controller:     SonataAdminBundle:CRUD
        translation:    SonataUserBundle
