twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        APPLICATION_NAME: 'Baby Tracker'
        VERSION: '0.0.1'
        APPLICATION_DESCRIPTION: 'Baby Track est une application permettant de suivre l''évolution des repas et sommeil de votre bébé.'
