language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit
    - $HOME/.npm
    - node_modules
    - vendor

matrix:
  fast_finish: true
  include:
    - php: 7.3
    - php: 7.4
    - php: nightly

  allow_failures:
    - php: nighlty

before_install:
  - nvm install --lts
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

before_script:
  - composer install --prefer-dist --no-interaction
  - npm install
  - composer install --prefer-dist --no-interaction
  - npm run dev
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:update --force --env=test
  - php bin/console doctrine:fixtures:load -n --env=test
  - ./cc-test-reporter before-build

script:
  - ./vendor/bin/simple-phpunit --coverage-text --colors
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT


