<?php

declare(strict_types=1);

namespace App\Admin;

use App\Entity\Baby;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Form\Type\ModelAutocompleteType;
use Sonata\AdminBundle\Show\ShowMapper;
use \Sonata\UserBundle\Admin\Model\UserAdmin as SonataUserAdmin;

final class UserAdmin extends SonataUserAdmin
{
  protected function configureFormFields(FormMapper $formMapper): void
  {
    parent::configureFormFields($formMapper); // TODO: Change the autogenerated stub

    $formMapper
      ->tab('Babies')
      ->with('Babies')
      ->add('babies', ModelAutocompleteType::class, [
        'property' => 'firstname',
        'multiple' => true,
        'to_string_callback' => function($entity, $property) {
          return $entity->getFirstname();
        },
      ])
      ->end()
      ->end();
  }


  protected function configureShowFields(ShowMapper $showMapper): void
  {
    parent::configureShowFields($showMapper); // TODO: Change the autogenerated stub
    $showMapper
      ->with('babies')
      ->add('babies')
      ->end();

  }


}
